import { parseMarkdownBlocks } from '@/utils/markdownBlocks';

describe('parseMarkdownBlocks', () => {
  it('parses a heading followed by a table, dropping the separator row and the empty header row', () => {
    const md = [
      '# Internship report — Ada Lovelace',
      '',
      '| | |',
      '|---|---|',
      '| Workplace | Acme Corp |',
    ].join('\n');
    expect(parseMarkdownBlocks(md)).toEqual([
      { type: 'h1', text: 'Internship report — Ada Lovelace' },
      { type: 'table', rows: [['Workplace', 'Acme Corp']] },
    ]);
  });

  it('drops a table\'s leading all-empty row while keeping its data row', () => {
    const md = ['| | |', '|---|---|', '| Workplace | Acme |'].join('\n');
    expect(parseMarkdownBlocks(md)).toEqual([
      { type: 'table', rows: [['Workplace', 'Acme']] },
    ]);
  });

  it('treats a line wrapped in underscores as a note, with the underscores removed', () => {
    const md =
      '_Generated by EngineerTrack on 2026-09-16. Counts and levels only; reflections, notes and journal text are not part of this report._';
    expect(parseMarkdownBlocks(md)).toEqual([
      {
        type: 'note',
        text: 'Generated by EngineerTrack on 2026-09-16. Counts and levels only; reflections, notes and journal text are not part of this report.',
      },
    ]);
  });

  it('ignores blank lines rather than emitting empty paragraphs', () => {
    const md = '# Title\n\n\np1\n\n\np2';
    expect(parseMarkdownBlocks(md)).toEqual([
      { type: 'h1', text: 'Title' },
      { type: 'p', text: 'p1' },
      { type: 'p', text: 'p2' },
    ]);
  });

  it('preserves a cell containing an em dash rather than mistaking it for a separator', () => {
    const md = '| Competency | Gap |\n|---|---|\n| Backend | — |';
    expect(parseMarkdownBlocks(md)).toEqual([
      { type: 'table', rows: [['Competency', 'Gap'], ['Backend', '—']] },
    ]);
  });

  it('splits two tables separated by a heading into two table blocks', () => {
    const md = [
      '| A | B |',
      '|---|---|',
      '| 1 | 2 |',
      '## Section',
      '| C | D |',
      '|---|---|',
      '| 3 | 4 |',
    ].join('\n');
    expect(parseMarkdownBlocks(md)).toEqual([
      { type: 'table', rows: [['A', 'B'], ['1', '2']] },
      { type: 'h2', text: 'Section' },
      { type: 'table', rows: [['C', 'D'], ['3', '4']] },
    ]);
  });

  it('renders an h2 heading', () => {
    expect(parseMarkdownBlocks('## Competencies')).toEqual([{ type: 'h2', text: 'Competencies' }]);
  });

  it('treats other non-empty lines as paragraphs', () => {
    expect(parseMarkdownBlocks('Submitted journals: 3')).toEqual([{ type: 'p', text: 'Submitted journals: 3' }]);
  });

  it('returns an empty array for blank input', () => {
    expect(parseMarkdownBlocks('')).toEqual([]);
    expect(parseMarkdownBlocks('   \n  \n')).toEqual([]);
  });
});
