// GENERATED by `supabase gen types` (see CLAUDE.md > Key Commands). Do not edit;
// regenerate after every SQL change so tsc sees the schema as it is.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      advisor_profiles: {
        Row: {
          department: string
          id: string
          title: string
          university: string
        }
        Insert: {
          department: string
          id: string
          title: string
          university: string
        }
        Update: {
          department?: string
          id?: string
          title?: string
          university?: string
        }
        Relationships: [
          {
            foreignKeyName: "advisor_profiles_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      assignment_submissions: {
        Row: {
          assignment_id: string
          id: string
          log_id: string | null
          mentor_level: number | null
          mentor_note: string | null
          reflection: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          self_level: number | null
          share_to_feed: boolean
          status: string
          student_id: string
          student_note: string | null
          submitted_at: string
        }
        Insert: {
          assignment_id: string
          id?: string
          log_id?: string | null
          mentor_level?: number | null
          mentor_note?: string | null
          reflection?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          self_level?: number | null
          share_to_feed?: boolean
          status: string
          student_id: string
          student_note?: string | null
          submitted_at?: string
        }
        Update: {
          assignment_id?: string
          id?: string
          log_id?: string | null
          mentor_level?: number | null
          mentor_note?: string | null
          reflection?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          self_level?: number | null
          share_to_feed?: boolean
          status?: string
          student_id?: string
          student_note?: string | null
          submitted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "assignment_submissions_assignment_id_fkey"
            columns: ["assignment_id"]
            isOneToOne: false
            referencedRelation: "group_assignments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "assignment_submissions_log_id_fkey"
            columns: ["log_id"]
            isOneToOne: false
            referencedRelation: "daily_logs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "assignment_submissions_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "assignment_submissions_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      competencies: {
        Row: {
          code: string
          display_order: number
          id: string
          name: string
        }
        Insert: {
          code: string
          display_order: number
          id?: string
          name: string
        }
        Update: {
          code?: string
          display_order?: number
          id?: string
          name?: string
        }
        Relationships: []
      }
      competency_kpis: {
        Row: {
          competency_id: string
          id: string
          kpi_index: number
          level: number
          statement: string
        }
        Insert: {
          competency_id: string
          id?: string
          kpi_index: number
          level: number
          statement: string
        }
        Update: {
          competency_id?: string
          id?: string
          kpi_index?: number
          level?: number
          statement?: string
        }
        Relationships: [
          {
            foreignKeyName: "competency_kpis_competency_id_fkey"
            columns: ["competency_id"]
            isOneToOne: false
            referencedRelation: "competencies"
            referencedColumns: ["id"]
          },
        ]
      }
      conversation_blocks: {
        Row: {
          blocker_id: string
          conversation_id: string
          created_at: string
        }
        Insert: {
          blocker_id: string
          conversation_id: string
          created_at?: string
        }
        Update: {
          blocker_id?: string
          conversation_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversation_blocks_blocker_id_fkey"
            columns: ["blocker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversation_blocks_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      conversation_participants: {
        Row: {
          added_at: string
          conversation_id: string
          user_id: string
        }
        Insert: {
          added_at?: string
          conversation_id: string
          user_id: string
        }
        Update: {
          added_at?: string
          conversation_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversation_participants_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversation_participants_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      conversation_reads: {
        Row: {
          conversation_id: string
          last_read_at: string
          user_id: string
        }
        Insert: {
          conversation_id: string
          last_read_at?: string
          user_id: string
        }
        Update: {
          conversation_id?: string
          last_read_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversation_reads_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversation_reads_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      conversations: {
        Row: {
          created_at: string
          created_by: string
          group_id: string
          id: string
          kind: string
          last_message_at: string | null
          pair_key: string | null
          subject_id: string | null
        }
        Insert: {
          created_at?: string
          created_by: string
          group_id: string
          id?: string
          kind: string
          last_message_at?: string | null
          pair_key?: string | null
          subject_id?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string
          group_id?: string
          id?: string
          kind?: string
          last_message_at?: string | null
          pair_key?: string | null
          subject_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "conversations_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "internship_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_subject_id_fkey"
            columns: ["subject_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      daily_logs: {
        Row: {
          activities_performed: string | null
          advisor_notes: string | null
          advisor_validated_at: string | null
          challenges_faced: string | null
          content: string
          created_at: string
          date: string
          hours_spent: number | null
          id: string
          skills_learned: string | null
          status: string
          student_id: string
          title: string
          updated_at: string
          xp_earned: number
        }
        Insert: {
          activities_performed?: string | null
          advisor_notes?: string | null
          advisor_validated_at?: string | null
          challenges_faced?: string | null
          content: string
          created_at?: string
          date: string
          hours_spent?: number | null
          id?: string
          skills_learned?: string | null
          status?: string
          student_id: string
          title: string
          updated_at?: string
          xp_earned?: number
        }
        Update: {
          activities_performed?: string | null
          advisor_notes?: string | null
          advisor_validated_at?: string | null
          challenges_faced?: string | null
          content?: string
          created_at?: string
          date?: string
          hours_spent?: number | null
          id?: string
          skills_learned?: string | null
          status?: string
          student_id?: string
          title?: string
          updated_at?: string
          xp_earned?: number
        }
        Relationships: [
          {
            foreignKeyName: "daily_logs_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      earned_badges: {
        Row: {
          badge_key: string
          earned_at: string
          id: string
          student_id: string
        }
        Insert: {
          badge_key: string
          earned_at?: string
          id?: string
          student_id: string
        }
        Update: {
          badge_key?: string
          earned_at?: string
          id?: string
          student_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "earned_badges_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      feed_attachments: {
        Row: {
          id: string
          kind: string
          mime: string | null
          name: string | null
          post_id: string
          size: number | null
          target: string
        }
        Insert: {
          id?: string
          kind: string
          mime?: string | null
          name?: string | null
          post_id: string
          size?: number | null
          target: string
        }
        Update: {
          id?: string
          kind?: string
          mime?: string | null
          name?: string | null
          post_id?: string
          size?: number | null
          target?: string
        }
        Relationships: [
          {
            foreignKeyName: "feed_attachments_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "feed_posts"
            referencedColumns: ["id"]
          },
        ]
      }
      feed_comments: {
        Row: {
          author_id: string
          body: string
          created_at: string
          id: string
          post_id: string
        }
        Insert: {
          author_id: string
          body: string
          created_at?: string
          id?: string
          post_id: string
        }
        Update: {
          author_id?: string
          body?: string
          created_at?: string
          id?: string
          post_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "feed_comments_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "feed_comments_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "feed_posts"
            referencedColumns: ["id"]
          },
        ]
      }
      feed_engagement_awards: {
        Row: {
          amount: number
          created_at: string
          kind: string
          post_id: string
          student_id: string
        }
        Insert: {
          amount: number
          created_at?: string
          kind: string
          post_id: string
          student_id: string
        }
        Update: {
          amount?: number
          created_at?: string
          kind?: string
          post_id?: string
          student_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "feed_engagement_awards_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "feed_posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "feed_engagement_awards_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      feed_likes: {
        Row: {
          created_at: string
          post_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          post_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          post_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "feed_likes_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "feed_posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "feed_likes_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      feed_poll_options: {
        Row: {
          id: string
          label: string
          position: number
          post_id: string
        }
        Insert: {
          id?: string
          label: string
          position: number
          post_id: string
        }
        Update: {
          id?: string
          label?: string
          position?: number
          post_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "feed_poll_options_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "feed_posts"
            referencedColumns: ["id"]
          },
        ]
      }
      feed_poll_votes: {
        Row: {
          created_at: string
          option_id: string
          post_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          option_id: string
          post_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          option_id?: string
          post_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "feed_poll_votes_option_id_fkey"
            columns: ["option_id"]
            isOneToOne: false
            referencedRelation: "feed_poll_options"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "feed_poll_votes_option_matches_post"
            columns: ["post_id", "option_id"]
            isOneToOne: false
            referencedRelation: "feed_poll_options"
            referencedColumns: ["post_id", "id"]
          },
          {
            foreignKeyName: "feed_poll_votes_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "feed_posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "feed_poll_votes_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      feed_posts: {
        Row: {
          assignment_id: string | null
          author_id: string
          body: string | null
          created_at: string
          group_id: string
          id: string
          kind: string
          published_at: string | null
          submission_id: string | null
        }
        Insert: {
          assignment_id?: string | null
          author_id: string
          body?: string | null
          created_at?: string
          group_id: string
          id?: string
          kind: string
          published_at?: string | null
          submission_id?: string | null
        }
        Update: {
          assignment_id?: string | null
          author_id?: string
          body?: string | null
          created_at?: string
          group_id?: string
          id?: string
          kind?: string
          published_at?: string | null
          submission_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "feed_posts_assignment_id_fkey"
            columns: ["assignment_id"]
            isOneToOne: true
            referencedRelation: "group_assignments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "feed_posts_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "feed_posts_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "internship_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "feed_posts_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: true
            referencedRelation: "assignment_submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      group_assignments: {
        Row: {
          created_at: string
          created_by: string
          criterion: string
          description: string | null
          document_name: string | null
          document_path: string | null
          due_date: string | null
          group_id: string
          id: string
          objective: string
          published_at: string | null
          title: string
          triplet_id: string
        }
        Insert: {
          created_at?: string
          created_by: string
          criterion: string
          description?: string | null
          document_name?: string | null
          document_path?: string | null
          due_date?: string | null
          group_id: string
          id?: string
          objective: string
          published_at?: string | null
          title: string
          triplet_id: string
        }
        Update: {
          created_at?: string
          created_by?: string
          criterion?: string
          description?: string | null
          document_name?: string | null
          document_path?: string | null
          due_date?: string | null
          group_id?: string
          id?: string
          objective?: string
          published_at?: string | null
          title?: string
          triplet_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_assignments_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "group_assignments_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "internship_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "group_assignments_triplet_id_fkey"
            columns: ["triplet_id"]
            isOneToOne: false
            referencedRelation: "kpi_triplets"
            referencedColumns: ["id"]
          },
        ]
      }
      group_competency_targets: {
        Row: {
          competency_id: string
          group_id: string
          id: string
          target_level: number
        }
        Insert: {
          competency_id: string
          group_id: string
          id?: string
          target_level: number
        }
        Update: {
          competency_id?: string
          group_id?: string
          id?: string
          target_level?: number
        }
        Relationships: [
          {
            foreignKeyName: "group_competency_targets_competency_id_fkey"
            columns: ["competency_id"]
            isOneToOne: false
            referencedRelation: "competencies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "group_competency_targets_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "internship_groups"
            referencedColumns: ["id"]
          },
        ]
      }
      group_memberships: {
        Row: {
          group_id: string
          id: string
          joined_at: string
          left_at: string | null
          student_id: string
        }
        Insert: {
          group_id: string
          id?: string
          joined_at?: string
          left_at?: string | null
          student_id: string
        }
        Update: {
          group_id?: string
          id?: string
          joined_at?: string
          left_at?: string | null
          student_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_memberships_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "internship_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "group_memberships_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      growth_awards: {
        Row: {
          checked_at: string
          earned_at: string
          evidence: Json
          family: string
          group_id: string
          label: string | null
          rule_version: number
          stage_id: string
          student_id: string
          target: number
          verified: boolean
        }
        Insert: {
          checked_at?: string
          earned_at?: string
          evidence: Json
          family: string
          group_id: string
          label?: string | null
          rule_version?: number
          stage_id: string
          student_id: string
          target: number
          verified?: boolean
        }
        Update: {
          checked_at?: string
          earned_at?: string
          evidence?: Json
          family?: string
          group_id?: string
          label?: string | null
          rule_version?: number
          stage_id?: string
          student_id?: string
          target?: number
          verified?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "growth_awards_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      growth_submission_events: {
        Row: {
          actor_id: string | null
          created_at: string
          id: number
          next_status: string
          previous_status: string | null
          submission_id: string
        }
        Insert: {
          actor_id?: string | null
          created_at?: string
          id?: never
          next_status: string
          previous_status?: string | null
          submission_id: string
        }
        Update: {
          actor_id?: string | null
          created_at?: string
          id?: never
          next_status?: string
          previous_status?: string | null
          submission_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "growth_submission_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "growth_submission_events_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "assignment_submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      growth_submission_path: {
        Row: {
          ever_approved: boolean
          improved: boolean
          resubmission_seen: boolean
          revision_seen: boolean
          submission_id: string
        }
        Insert: {
          ever_approved?: boolean
          improved?: boolean
          resubmission_seen?: boolean
          revision_seen?: boolean
          submission_id: string
        }
        Update: {
          ever_approved?: boolean
          improved?: boolean
          resubmission_seen?: boolean
          revision_seen?: boolean
          submission_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "growth_submission_path_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: true
            referencedRelation: "assignment_submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      internship_closures: {
        Row: {
          closed_at: string
          closed_by: string
          group_id: string
          id: string
          reopen_reason: string | null
          reopened_at: string | null
          reopened_by: string | null
          report_md: string
          report_version: number
          student_id: string
        }
        Insert: {
          closed_at?: string
          closed_by: string
          group_id: string
          id?: string
          reopen_reason?: string | null
          reopened_at?: string | null
          reopened_by?: string | null
          report_md: string
          report_version?: number
          student_id: string
        }
        Update: {
          closed_at?: string
          closed_by?: string
          group_id?: string
          id?: string
          reopen_reason?: string | null
          reopened_at?: string | null
          reopened_by?: string | null
          report_md?: string
          report_version?: number
          student_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "internship_closures_closed_by_fkey"
            columns: ["closed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "internship_closures_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "internship_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "internship_closures_reopened_by_fkey"
            columns: ["reopened_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "internship_closures_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      internship_day_events: {
        Row: {
          actor_id: string
          created_at: string
          day_id: string
          event_type: string
          id: string
          next_value: Json | null
          note: string
          previous_value: Json | null
        }
        Insert: {
          actor_id: string
          created_at?: string
          day_id: string
          event_type: string
          id?: string
          next_value?: Json | null
          note?: string
          previous_value?: Json | null
        }
        Update: {
          actor_id?: string
          created_at?: string
          day_id?: string
          event_type?: string
          id?: string
          next_value?: Json | null
          note?: string
          previous_value?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "internship_day_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "internship_day_events_day_id_fkey"
            columns: ["day_id"]
            isOneToOne: false
            referencedRelation: "internship_days"
            referencedColumns: ["id"]
          },
        ]
      }
      internship_days: {
        Row: {
          attachment: Json | null
          attendance: string
          attendance_at: string | null
          attendance_by: string | null
          attendance_note: string
          check_in_at: string | null
          competency_name: string | null
          correction_requested: boolean
          day_date: string
          experience: string
          id: string
          learning: string
          log_status: string
          next_step: string
          placement_id: string
          report_reason: string
          reported_at: string
          reported_by: string
          student_id: string
          submitted_at: string | null
          support_level: number | null
          task_id: string | null
          task_title: string | null
          updated_at: string
          version: number
        }
        Insert: {
          attachment?: Json | null
          attendance?: string
          attendance_at?: string | null
          attendance_by?: string | null
          attendance_note?: string
          check_in_at?: string | null
          competency_name?: string | null
          correction_requested?: boolean
          day_date: string
          experience?: string
          id?: string
          learning?: string
          log_status?: string
          next_step?: string
          placement_id: string
          report_reason?: string
          reported_at?: string
          reported_by: string
          student_id: string
          submitted_at?: string | null
          support_level?: number | null
          task_id?: string | null
          task_title?: string | null
          updated_at?: string
          version?: number
        }
        Update: {
          attachment?: Json | null
          attendance?: string
          attendance_at?: string | null
          attendance_by?: string | null
          attendance_note?: string
          check_in_at?: string | null
          competency_name?: string | null
          correction_requested?: boolean
          day_date?: string
          experience?: string
          id?: string
          learning?: string
          log_status?: string
          next_step?: string
          placement_id?: string
          report_reason?: string
          reported_at?: string
          reported_by?: string
          student_id?: string
          submitted_at?: string | null
          support_level?: number | null
          task_id?: string | null
          task_title?: string | null
          updated_at?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "internship_days_attendance_by_fkey"
            columns: ["attendance_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "internship_days_placement_id_fkey"
            columns: ["placement_id"]
            isOneToOne: false
            referencedRelation: "internship_placements"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "internship_days_reported_by_fkey"
            columns: ["reported_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "internship_days_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      internship_groups: {
        Row: {
          advisor_id: string
          created_at: string
          id: string
          is_archived: boolean
          join_code: string
          name: string
          term: string | null
          updated_at: string
        }
        Insert: {
          advisor_id: string
          created_at?: string
          id?: string
          is_archived?: boolean
          join_code?: string
          name: string
          term?: string | null
          updated_at?: string
        }
        Update: {
          advisor_id?: string
          created_at?: string
          id?: string
          is_archived?: boolean
          join_code?: string
          name?: string
          term?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "internship_groups_advisor_id_fkey"
            columns: ["advisor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      internship_placements: {
        Row: {
          company_name: string
          created_at: string
          end_date: string
          group_id: string
          id: string
          mentor_id: string
          start_date: string
          student_id: string
          timezone: string
        }
        Insert: {
          company_name: string
          created_at?: string
          end_date: string
          group_id: string
          id?: string
          mentor_id: string
          start_date: string
          student_id: string
          timezone: string
        }
        Update: {
          company_name?: string
          created_at?: string
          end_date?: string
          group_id?: string
          id?: string
          mentor_id?: string
          start_date?: string
          student_id?: string
          timezone?: string
        }
        Relationships: [
          {
            foreignKeyName: "internship_placements_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "internship_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "internship_placements_mentor_id_fkey"
            columns: ["mentor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "internship_placements_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      kpi_observations: {
        Row: {
          assignment_submission_id: string | null
          id: string
          kpi_id: string
          log_id: string | null
          observed_at: string
          observed_by: string
          student_id: string
        }
        Insert: {
          assignment_submission_id?: string | null
          id?: string
          kpi_id: string
          log_id?: string | null
          observed_at?: string
          observed_by: string
          student_id: string
        }
        Update: {
          assignment_submission_id?: string | null
          id?: string
          kpi_id?: string
          log_id?: string | null
          observed_at?: string
          observed_by?: string
          student_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "kpi_observations_assignment_submission_fk"
            columns: ["assignment_submission_id"]
            isOneToOne: false
            referencedRelation: "assignment_submissions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kpi_observations_kpi_id_fkey"
            columns: ["kpi_id"]
            isOneToOne: false
            referencedRelation: "competency_kpis"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kpi_observations_log_id_fkey"
            columns: ["log_id"]
            isOneToOne: false
            referencedRelation: "daily_logs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kpi_observations_observed_by_fkey"
            columns: ["observed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kpi_observations_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      kpi_triplets: {
        Row: {
          criterion: string
          id: string
          kpi_id: string
          objective: string
          task: string
          triplet_index: number
        }
        Insert: {
          criterion: string
          id?: string
          kpi_id: string
          objective: string
          task: string
          triplet_index: number
        }
        Update: {
          criterion?: string
          id?: string
          kpi_id?: string
          objective?: string
          task?: string
          triplet_index?: number
        }
        Relationships: [
          {
            foreignKeyName: "kpi_triplets_kpi_id_fkey"
            columns: ["kpi_id"]
            isOneToOne: false
            referencedRelation: "competency_kpis"
            referencedColumns: ["id"]
          },
        ]
      }
      leaderboard_public: {
        Row: {
          avatar_url: string | null
          current_level: number
          current_streak: number
          first_name: string
          id: string
          last_name: string
          total_xp: number
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          current_level?: number
          current_streak?: number
          first_name?: string
          id: string
          last_name?: string
          total_xp?: number
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          current_level?: number
          current_streak?: number
          first_name?: string
          id?: string
          last_name?: string
          total_xp?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "leaderboard_public_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      log_documents: {
        Row: {
          created_at: string
          file_name: string
          file_size: number
          file_type: string
          id: string
          log_id: string | null
          submission_id: string | null
          uri: string
        }
        Insert: {
          created_at?: string
          file_name: string
          file_size: number
          file_type: string
          id?: string
          log_id?: string | null
          submission_id?: string | null
          uri: string
        }
        Update: {
          created_at?: string
          file_name?: string
          file_size?: number
          file_type?: string
          id?: string
          log_id?: string | null
          submission_id?: string | null
          uri?: string
        }
        Relationships: [
          {
            foreignKeyName: "log_documents_log_id_fkey"
            columns: ["log_id"]
            isOneToOne: false
            referencedRelation: "daily_logs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "log_documents_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "assignment_submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      log_photos: {
        Row: {
          caption: string | null
          created_at: string
          id: string
          log_id: string | null
          submission_id: string | null
          uri: string
        }
        Insert: {
          caption?: string | null
          created_at?: string
          id?: string
          log_id?: string | null
          submission_id?: string | null
          uri: string
        }
        Update: {
          caption?: string | null
          created_at?: string
          id?: string
          log_id?: string | null
          submission_id?: string | null
          uri?: string
        }
        Relationships: [
          {
            foreignKeyName: "log_photos_log_id_fkey"
            columns: ["log_id"]
            isOneToOne: false
            referencedRelation: "daily_logs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "log_photos_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "assignment_submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      mentor_feedbacks: {
        Row: {
          areas_of_excellence: string | null
          comments: string | null
          created_at: string
          id: string
          is_approved: boolean
          log_id: string
          mentor_id: string
          rating: number
          revision_notes: string | null
          revision_required: boolean
        }
        Insert: {
          areas_of_excellence?: string | null
          comments?: string | null
          created_at?: string
          id?: string
          is_approved?: boolean
          log_id: string
          mentor_id: string
          rating: number
          revision_notes?: string | null
          revision_required?: boolean
        }
        Update: {
          areas_of_excellence?: string | null
          comments?: string | null
          created_at?: string
          id?: string
          is_approved?: boolean
          log_id?: string
          mentor_id?: string
          rating?: number
          revision_notes?: string | null
          revision_required?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "mentor_feedbacks_log_id_fkey"
            columns: ["log_id"]
            isOneToOne: false
            referencedRelation: "daily_logs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mentor_feedbacks_mentor_id_fkey"
            columns: ["mentor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      mentor_profiles: {
        Row: {
          company_name: string
          department: string
          id: string
          position: string
        }
        Insert: {
          company_name: string
          department: string
          id: string
          position: string
        }
        Update: {
          company_name?: string
          department?: string
          id?: string
          position?: string
        }
        Relationships: [
          {
            foreignKeyName: "mentor_profiles_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          body: string
          conversation_id: string
          created_at: string
          id: string
          sender_id: string
        }
        Insert: {
          body: string
          conversation_id: string
          created_at?: string
          id?: string
          sender_id: string
        }
        Update: {
          body?: string
          conversation_id?: string
          created_at?: string
          id?: string
          sender_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string
          created_at: string
          data: Json | null
          id: string
          is_read: boolean
          title: string
          type: string
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          data?: Json | null
          id?: string
          is_read?: boolean
          title: string
          type: string
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          data?: Json | null
          id?: string
          is_read?: boolean
          title?: string
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      poll_options: {
        Row: {
          id: string
          option_text: string
          question_id: string
          sort_order: number
        }
        Insert: {
          id?: string
          option_text: string
          question_id: string
          sort_order?: number
        }
        Update: {
          id?: string
          option_text?: string
          question_id?: string
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "poll_options_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "poll_questions"
            referencedColumns: ["id"]
          },
        ]
      }
      poll_questions: {
        Row: {
          correct_option_id: string | null
          created_at: string
          id: string
          poll_id: string
          question_text: string
          question_type: string
          sort_order: number
        }
        Insert: {
          correct_option_id?: string | null
          created_at?: string
          id?: string
          poll_id: string
          question_text: string
          question_type: string
          sort_order?: number
        }
        Update: {
          correct_option_id?: string | null
          created_at?: string
          id?: string
          poll_id?: string
          question_text?: string
          question_type?: string
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "poll_questions_poll_id_fkey"
            columns: ["poll_id"]
            isOneToOne: false
            referencedRelation: "polls"
            referencedColumns: ["id"]
          },
        ]
      }
      poll_responses: {
        Row: {
          answers: Json
          id: string
          poll_id: string
          score: number | null
          submitted_at: string
          user_id: string
        }
        Insert: {
          answers?: Json
          id?: string
          poll_id: string
          score?: number | null
          submitted_at?: string
          user_id: string
        }
        Update: {
          answers?: Json
          id?: string
          poll_id?: string
          score?: number | null
          submitted_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "poll_responses_poll_id_fkey"
            columns: ["poll_id"]
            isOneToOne: false
            referencedRelation: "polls"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "poll_responses_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      polls: {
        Row: {
          created_at: string
          creator_id: string
          description: string | null
          ends_at: string | null
          group_id: string | null
          id: string
          is_active: boolean
          poll_type: string
          starts_at: string
          target_role: string
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          creator_id: string
          description?: string | null
          ends_at?: string | null
          group_id?: string | null
          id?: string
          is_active?: boolean
          poll_type: string
          starts_at?: string
          target_role?: string
          title: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          creator_id?: string
          description?: string | null
          ends_at?: string | null
          group_id?: string | null
          id?: string
          is_active?: boolean
          poll_type?: string
          starts_at?: string
          target_role?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "polls_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "polls_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "internship_groups"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          consent_version: string | null
          consented_at: string | null
          created_at: string
          email: string
          expo_push_token: string | null
          first_name: string
          id: string
          language: string
          last_name: string
          role: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          consent_version?: string | null
          consented_at?: string | null
          created_at?: string
          email: string
          expo_push_token?: string | null
          first_name: string
          id: string
          language?: string
          last_name: string
          role: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          consent_version?: string | null
          consented_at?: string | null
          created_at?: string
          email?: string
          expo_push_token?: string | null
          first_name?: string
          id?: string
          language?: string
          last_name?: string
          role?: string
          updated_at?: string
        }
        Relationships: []
      }
      profiles_public: {
        Row: {
          avatar_url: string | null
          first_name: string
          id: string
          last_name: string
          role: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          first_name?: string
          id: string
          last_name?: string
          role?: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          first_name?: string
          id?: string
          last_name?: string
          role?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_public_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      revision_history: {
        Row: {
          id: string
          log_id: string
          new_content: string
          previous_content: string
          reason: string
          revised_at: string
        }
        Insert: {
          id?: string
          log_id: string
          new_content: string
          previous_content: string
          reason: string
          revised_at?: string
        }
        Update: {
          id?: string
          log_id?: string
          new_content?: string
          previous_content?: string
          reason?: string
          revised_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "revision_history_log_id_fkey"
            columns: ["log_id"]
            isOneToOne: false
            referencedRelation: "daily_logs"
            referencedColumns: ["id"]
          },
        ]
      }
      self_assessments: {
        Row: {
          created_at: string
          id: string
          log_id: string
          reflection_notes: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          log_id: string
          reflection_notes?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          log_id?: string
          reflection_notes?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "self_assessments_log_id_fkey"
            columns: ["log_id"]
            isOneToOne: true
            referencedRelation: "daily_logs"
            referencedColumns: ["id"]
          },
        ]
      }
      student_avatar_preferences: {
        Row: {
          avatar_id: string
          student_id: string
          updated_at: string
        }
        Insert: {
          avatar_id: string
          student_id: string
          updated_at?: string
        }
        Update: {
          avatar_id?: string
          student_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "student_avatar_preferences_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      student_codes: {
        Row: {
          code: string
          created_at: string | null
          id: string
          is_active: boolean | null
          student_id: string
        }
        Insert: {
          code?: string
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          student_id: string
        }
        Update: {
          code?: string
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          student_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "student_codes_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      student_profiles: {
        Row: {
          advisor_id: string | null
          company_address: string | null
          company_name: string
          company_sector: string | null
          current_level: number
          current_streak: number
          department: string
          department_branch: string | null
          faculty: string | null
          id: string
          internship_end_date: string
          internship_start_date: string
          longest_streak: number
          mentor_id: string | null
          mentor_linked_at: string | null
          student_id: string
          total_xp: number
          university: string
        }
        Insert: {
          advisor_id?: string | null
          company_address?: string | null
          company_name: string
          company_sector?: string | null
          current_level?: number
          current_streak?: number
          department: string
          department_branch?: string | null
          faculty?: string | null
          id: string
          internship_end_date: string
          internship_start_date: string
          longest_streak?: number
          mentor_id?: string | null
          mentor_linked_at?: string | null
          student_id: string
          total_xp?: number
          university: string
        }
        Update: {
          advisor_id?: string | null
          company_address?: string | null
          company_name?: string
          company_sector?: string | null
          current_level?: number
          current_streak?: number
          department?: string
          department_branch?: string | null
          faculty?: string | null
          id?: string
          internship_end_date?: string
          internship_start_date?: string
          longest_streak?: number
          mentor_id?: string | null
          mentor_linked_at?: string | null
          student_id?: string
          total_xp?: number
          university?: string
        }
        Relationships: [
          {
            foreignKeyName: "student_profiles_advisor_id_fkey"
            columns: ["advisor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "student_profiles_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "student_profiles_mentor_id_fkey"
            columns: ["mentor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      xp_transactions: {
        Row: {
          amount: number
          created_at: string
          id: string
          log_id: string | null
          reason: string
          student_id: string
        }
        Insert: {
          amount: number
          created_at?: string
          id?: string
          log_id?: string | null
          reason: string
          student_id: string
        }
        Update: {
          amount?: number
          created_at?: string
          id?: string
          log_id?: string | null
          reason?: string
          student_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "xp_transactions_log_id_fkey"
            columns: ["log_id"]
            isOneToOne: false
            referencedRelation: "daily_logs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "xp_transactions_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      advisor_student_avatars: { Args: { p_group_id?: string }; Returns: Json }
      assignment_has_submissions: {
        Args: { p_assignment_id: string }
        Returns: boolean
      }
      award_badge_internal: {
        Args: { p_badge_key: string; p_student: string }
        Returns: undefined
      }
      award_xp_internal: {
        Args: {
          p_amount: number
          p_log?: string
          p_reason: string
          p_student: string
        }
        Returns: undefined
      }
      block_conversation: {
        Args: { p_block: boolean; p_conversation_id: string }
        Returns: undefined
      }
      broadcast_message: {
        Args: { p_body: string; p_recipients: string[] }
        Returns: Json
      }
      build_internship_report: {
        Args: { p_group_id: string; p_student_id: string }
        Returns: string
      }
      calculate_level: { Args: { p_xp: number }; Returns: number }
      can_access_conversation: {
        Args: { p_conversation_id: string }
        Returns: boolean
      }
      can_message: {
        Args: { p_group_id: string; p_other: string; p_user: string }
        Returns: string
      }
      can_see_post: { Args: { p_post_id: string }; Returns: boolean }
      can_view_competency: { Args: { p_student_id: string }; Returns: boolean }
      can_view_self_assessment: { Args: { p_log_id: string }; Returns: boolean }
      close_internship: {
        Args: { p_group_id: string; p_student_id: string }
        Returns: Json
      }
      close_membership: {
        Args: { p_membership_id: string }
        Returns: undefined
      }
      closure_level_word: { Args: { p_level: number }; Returns: string }
      closure_reached_level: {
        Args: { p_competency_id: string; p_student_id: string }
        Returns: number
      }
      competency_self_vs_mentor: {
        Args: { p_student_id: string }
        Returns: Json[]
      }
      conversation_other: {
        Args: { p_conversation_id: string; p_user: string }
        Returns: string
      }
      count_deletable_conversations: {
        Args: { p_group_id: string; p_student_id?: string }
        Returns: number
      }
      create_feed_post: {
        Args: {
          p_attachments?: Json
          p_body: string
          p_draft?: boolean
          p_group_id: string
          p_kind: string
          p_options?: string[]
        }
        Returns: string
      }
      feed_engagement_award: {
        Args: {
          p_amount: number
          p_cap: number
          p_kind: string
          p_post: string
          p_student: string
        }
        Returns: undefined
      }
      feed_publish_assignment: {
        Args: { p_assignment_id: string }
        Returns: string
      }
      feed_publish_post: { Args: { p_post_id: string }; Returns: undefined }
      feed_publish_submission: {
        Args: { p_submission_id: string }
        Returns: string
      }
      feed_shares_evidence: {
        Args: { p_assignment: string; p_student: string }
        Returns: boolean
      }
      generate_random_code: { Args: { length: number }; Returns: string }
      get_competency_progress: {
        Args: { p_student_id: string }
        Returns: {
          competency_code: string
          competency_id: string
          competency_name: string
          current_level: number
          target_level: number
        }[]
      }
      get_internship_report: {
        Args: { p_group_id: string; p_student_id: string }
        Returns: string
      }
      get_my_group_leaderboard: {
        Args: { p_limit?: number }
        Returns: {
          avatar_url: string
          current_level: number
          current_streak: number
          first_name: string
          id: string
          last_initial: string
          total_xp: number
        }[]
      }
      get_my_student_code: {
        Args: never
        Returns: {
          code: string
        }[]
      }
      get_user_role: { Args: never; Returns: string }
      get_working_kpis: {
        Args: { p_student_id: string }
        Returns: {
          competency_id: string
          competency_name: string
          kpi_id: string
          kpi_index: number
          level: number
          statement: string
        }[]
      }
      group_assignment_counts: {
        Args: { p_group_id: string }
        Returns: {
          approved: number
          assignment_id: string
          needs_revision: number
          submitted: number
        }[]
      }
      internship_can_day: { Args: { p_day: string }; Returns: boolean }
      internship_can_student: {
        Args: { p_actor: string; p_student: string }
        Returns: boolean
      }
      internship_closed: {
        Args: { p_group_id: string; p_student_id: string }
        Returns: boolean
      }
      internship_closure_status: {
        Args: { p_group_id: string; p_student_id: string }
        Returns: Json
      }
      internship_events: { Args: { p_day: string }; Returns: Json }
      internship_file_allowed: {
        Args: { p_path: string; p_write: boolean }
        Returns: boolean
      }
      internship_group_attendance: {
        Args: { p_group_id: string }
        Returns: Json
      }
      internship_note: {
        Args: {
          p_correction?: boolean
          p_day: string
          p_note: string
          p_version: number
        }
        Returns: undefined
      }
      internship_notify: {
        Args: {
          p_body: string
          p_data: Json
          p_title: string
          p_type: string
          p_user: string
        }
        Returns: undefined
      }
      internship_open_day: {
        Args: {
          p_date: string
          p_reason?: string
          p_student_id: string
          p_timezone: string
        }
        Returns: string
      }
      internship_people: { Args: never; Returns: Json }
      internship_review: {
        Args: { p_days: Json; p_note?: string; p_status: string }
        Returns: undefined
      }
      internship_save_log: {
        Args: {
          p_attachment?: Json
          p_day: string
          p_experience: string
          p_learning: string
          p_next_step: string
          p_reason?: string
          p_submit: boolean
          p_support: number
          p_task?: string
          p_version: number
        }
        Returns: undefined
      }
      internship_tasks: { Args: { p_day: string }; Returns: Json }
      internship_totals: { Args: { p_student_id: string }; Returns: Json }
      internship_week: {
        Args: { p_from: string; p_student_id: string }
        Returns: Json
      }
      internship_weekdays: {
        Args: { p_from: string; p_to: string }
        Returns: number
      }
      is_advisor_of: { Args: { student_uuid: string }; Returns: boolean }
      is_group_advisor_of: { Args: { target: string }; Returns: boolean }
      is_log_owner: { Args: { p_log_id: string }; Returns: boolean }
      is_member_of_group: { Args: { p_group_id: string }; Returns: boolean }
      is_mentor_of: { Args: { student_uuid: string }; Returns: boolean }
      join_group_by_code: {
        Args: { p_code: string }
        Returns: {
          advisor_name: string
          id: string
          name: string
          term: string
        }[]
      }
      link_student_by_code: {
        Args: { p_code: string; p_role: string }
        Returns: {
          student_id: string
          student_name: string
        }[]
      }
      list_case_candidates: { Args: { p_group_id: string }; Returns: Json[] }
      list_conversations: { Args: { p_group_id?: string }; Returns: Json[] }
      list_feed_pending: { Args: { p_group_id: string }; Returns: Json[] }
      list_feed_posts: {
        Args: { p_before?: string; p_group_id: string; p_limit?: number }
        Returns: Json[]
      }
      list_mentor_message_contacts: { Args: never; Returns: Json[] }
      list_message_contacts: { Args: { p_group_id: string }; Returns: Json[] }
      list_messages: {
        Args: { p_before?: string; p_conversation_id: string; p_limit?: number }
        Returns: Json[]
      }
      mark_conversation_read: {
        Args: { p_conversation_id: string }
        Returns: undefined
      }
      mentors_a_member_of_group: {
        Args: { p_group_id: string }
        Returns: boolean
      }
      my_growth_journey: { Args: never; Returns: Json }
      my_student_avatar: { Args: never; Returns: Json }
      open_case: {
        Args: { p_group_id: string; p_student_id: string }
        Returns: string
      }
      open_conversation: {
        Args: { p_group_id: string; p_other_id: string }
        Returns: string
      }
      owns_group: { Args: { p_group_id: string }; Returns: boolean }
      publish_assignments: { Args: { p_ids: string[] }; Returns: number }
      publish_feed_post: { Args: { p_post_id: string }; Returns: undefined }
      record_consent: { Args: { p_version: string }; Returns: undefined }
      record_kpi_observations: {
        Args: { p_kpi_ids: string[]; p_log_id: string; p_student_id: string }
        Returns: undefined
      }
      remove_feed_post: { Args: { p_post_id: string }; Returns: undefined }
      reopen_internship: {
        Args: { p_group_id: string; p_reason: string; p_student_id: string }
        Returns: undefined
      }
      review_assignment: {
        Args: {
          p_approved: boolean
          p_level?: number
          p_note?: string
          p_submission_id: string
        }
        Returns: undefined
      }
      send_message: {
        Args: { p_body: string; p_conversation_id: string }
        Returns: string
      }
      set_student_avatar: { Args: { p_avatar_id: string }; Returns: Json }
      set_submission_sharing: {
        Args: { p_share: boolean; p_submission_id: string }
        Returns: undefined
      }
      shares_group_with: { Args: { target: string }; Returns: boolean }
      submit_assignment: {
        Args: {
          p_assignment_id: string
          p_documents?: Json
          p_note?: string
          p_photos?: Json
          p_reflection?: string
          p_self_level?: number
        }
        Returns: string
      }
      sync_my_growth_awards: { Args: never; Returns: Json }
      unread_message_count: { Args: never; Returns: number }
      validate_group_code: {
        Args: { p_code: string }
        Returns: {
          advisor_name: string
          id: string
          name: string
          term: string
        }[]
      }
      vote_feed_poll: {
        Args: { p_option_id: string; p_post_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
