#!/usr/bin/env python3
"""Generate docs/task-triplets-migration.sql from .tmp/triplets.json.

Do not hand-edit the output. A hand-typed seed is where a wrong KPI link
enters silently, and nothing downstream would notice.

Usage:
    python scripts/generate-triplet-seed.py .tmp/triplets.json > docs/task-triplets-migration.sql
"""
import json
import sys
from collections import Counter

# The JSON artifacts carry the competency's DISPLAY NAME, not its code, and
# competencies.code holds the code. Joining on the name matches nothing and the
# INSERT silently adds zero rows, which no count of the generated VALUES lines
# can detect. scripts/generate-competency-seed.py carries the same map for the
# same reason; keep the two in step.
BY_NAME = {
    "Engineering Problem Solving": "problem_solving",
    "Technical Documentation": "documentation",
    "Professional Communication": "communication",
    "Digital Tool Proficiency": "digital_tools",
    "Responsibility & Ethics": "ethics",
    "Collaboration & Teamwork": "teamwork",
}


def sql_quote(value):
    return "'" + str(value).replace("'", "''") + "'"


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: generate-triplet-seed.py <triplets.json>")

    # The source text contains curly quotes and dashes. On Windows, stdout
    # defaults to the console codepage (cp1254 here), so a redirect writes
    # those bytes in a legacy encoding and Postgres reads mojibake — or
    # rejects the file outright. Nothing downstream would flag it, because a
    # mis-encoded character is still a character.
    sys.stdout.reconfigure(encoding="utf-8", newline="\n")

    triplets = json.load(open(sys.argv[1], encoding="utf-8"))

    unknown = {t["competency"] for t in triplets} - set(BY_NAME)
    if unknown:
        sys.exit("unmapped competency names: %s" % sorted(unknown))

    by_kpi = {}
    for t in triplets:
        by_kpi.setdefault((t["competency"], t["level"], t["kpi_index"]), []).append(t)

    if len(by_kpi) != 48:
        sys.exit("expected 48 KPIs, got %d" % len(by_kpi))

    counts = Counter({k: len(v) for k, v in by_kpi.items()})
    outside = {k: n for k, n in counts.items() if not 8 <= n <= 12}
    if outside:
        sys.exit("KPIs outside the 8-12 band: %s" % outside)

    values = []
    for key in sorted(by_kpi):
        name, level, kpi_index = key
        code = BY_NAME[name]
        # Document order within the KPI. by_kpi preserves insertion order, and
        # the extractor walks tables in (page, order) sequence, so triplet_index
        # follows the document rather than any sort of the text.
        for n, t in enumerate(by_kpi[key], start=1):
            values.append(
                "  (%s, %d, %d, %d, %s, %s, %s)"
                % (sql_quote(code), level, kpi_index, n,
                   sql_quote(t["objective"]), sql_quote(t["task"]),
                   sql_quote(t["criterion"]))
            )

    print("-- docs/task-triplets-migration.sql")
    print("-- Generated by scripts/generate-triplet-seed.py. Do not hand-edit.")
    print("-- Run AFTER docs/competency-framework-migration.sql. Idempotent.")
    print("--")
    print("-- The Learning Objective -> Task -> Assessment Criterion triplets, the")
    print("-- pedagogical unit the internship content document is built on. Read-only:")
    print("-- an advisor derives tasks from these but never edits them.")
    print("--")
    print("-- %d rows across 48 KPIs." % len(values))
    print()
    print("CREATE TABLE IF NOT EXISTS kpi_triplets (")
    print("  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    print("  kpi_id        UUID NOT NULL REFERENCES competency_kpis(id) ON DELETE CASCADE,")
    print("  triplet_index INT  NOT NULL,")
    print("  objective     TEXT NOT NULL,")
    print("  task          TEXT NOT NULL,")
    print("  criterion     TEXT NOT NULL,")
    print("  UNIQUE (kpi_id, triplet_index)")
    print(");")
    print()
    print("ALTER TABLE kpi_triplets ENABLE ROW LEVEL SECURITY;")
    print()
    print("-- Reference data, like the framework itself: a SELECT policy and no write")
    print("-- policy at all. This is a project deliverable, not app state.")
    print('DROP POLICY IF EXISTS "kpi triplets read" ON kpi_triplets;')
    print('CREATE POLICY "kpi triplets read" ON kpi_triplets')
    print("  FOR SELECT TO authenticated USING (true);")
    print()
    print("INSERT INTO kpi_triplets (kpi_id, triplet_index, objective, task, criterion)")
    print("SELECT k.id, v.triplet_index, v.objective, v.task, v.criterion")
    print("FROM (VALUES")
    print(",\n".join(values))
    print(") AS v(code, level, kpi_index, triplet_index, objective, task, criterion)")
    print("JOIN competencies c ON c.code = v.code")
    print("JOIN competency_kpis k ON k.competency_id = c.id")
    print("  AND k.level = v.level AND k.kpi_index = v.kpi_index")
    print("ON CONFLICT (kpi_id, triplet_index) DO UPDATE SET")
    print("  objective = EXCLUDED.objective,")
    print("  task = EXCLUDED.task,")
    print("  criterion = EXCLUDED.criterion;")


if __name__ == "__main__":
    main()
