#!/usr/bin/env python3
"""Turn kpis.json into the seed half of docs/competency-framework-migration.sql.

The 48 rows are generated, never typed. A hand-written seed is where a wrong
level or a swapped KPI index enters silently, and nothing downstream would
notice: the app would simply assess against the wrong rung of the ladder.

Run:  python scripts/generate-competency-seed.py .tmp/kpis.json
Prints SQL on stdout.
"""
import json
import re
import sys
from collections import Counter

# code, display name. Order is the document's own; the framework states the
# competencies are non-hierarchical, so display_order is presentation only.
COMPETENCIES = [
    ("problem_solving", "Engineering Problem Solving"),
    ("documentation", "Technical Documentation"),
    ("communication", "Professional Communication"),
    ("digital_tools", "Digital Tool Proficiency"),
    ("ethics", "Responsibility & Ethics"),
    ("teamwork", "Collaboration & Teamwork"),
]
BY_NAME = {name: code for code, name in COMPETENCIES}


def sql_quote(value):
    return "'" + value.replace("'", "''") + "'"


def main():
    kpis = json.load(open(sys.argv[1], encoding="utf-8"))

    if len(kpis) != 48:
        sys.exit("expected 48 KPIs, got %d" % len(kpis))
    per_competency = Counter(k["competency"] for k in kpis)
    for _, name in COMPETENCIES:
        if per_competency.get(name) != 8:
            sys.exit("%s has %d KPIs, expected 8" % (name, per_competency.get(name, 0)))
    per_level = Counter(k["level"] for k in kpis)
    for level in (1, 2, 3, 4):
        if per_level.get(level) != 12:
            sys.exit("level %d has %d KPIs, expected 12" % (level, per_level.get(level, 0)))
    seen = {(k["competency"], k["level"], k["kpi_index"]) for k in kpis}
    if len(seen) != 48:
        sys.exit("duplicate (competency, level, kpi_index) in the source data")

    print("-- Generated by scripts/generate-competency-seed.py. Do not hand-edit.")
    print("INSERT INTO competencies (code, name, display_order) VALUES")
    rows = ["  (%s, %s, %d)" % (sql_quote(code), sql_quote(name), i + 1)
            for i, (code, name) in enumerate(COMPETENCIES)]
    print(",\n".join(rows))
    print("ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,")
    print("  display_order = EXCLUDED.display_order;")
    print()
    print("INSERT INTO competency_kpis (competency_id, level, kpi_index, statement)")
    print("SELECT c.id, v.level, v.kpi_index, v.statement")
    print("FROM (VALUES")
    values = []
    for k in kpis:
        values.append("  (%s, %d, %d, %s)" % (
            sql_quote(BY_NAME[k["competency"]]), k["level"], k["kpi_index"],
            sql_quote(re.sub(r"\s+", " ", k["statement"]).strip())))
    print(",\n".join(values))
    print(") AS v(code, level, kpi_index, statement)")
    print("JOIN competencies c ON c.code = v.code")
    print("ON CONFLICT (competency_id, level, kpi_index)")
    print("  DO UPDATE SET statement = EXCLUDED.statement;")


if __name__ == "__main__":
    main()
