-- docs/competency-framework-migration.sql
-- The Engineering Internship Competency Framework as reference data.
-- Idempotent; safe to re-run.
--
-- Six competencies, four levels each, two KPIs per level = 48 rows. The seed at
-- the bottom is generated by scripts/generate-competency-seed.py from the
-- source PDF — do not hand-edit it. A hand-typed seed is where a wrong level or
-- a swapped KPI index enters silently, and nothing downstream would notice.

CREATE TABLE IF NOT EXISTS competencies (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code          TEXT UNIQUE NOT NULL,
  name          TEXT NOT NULL,
  display_order INT  NOT NULL
);

CREATE TABLE IF NOT EXISTS competency_kpis (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  competency_id UUID NOT NULL REFERENCES competencies(id) ON DELETE CASCADE,
  level         INT  NOT NULL CHECK (level BETWEEN 1 AND 4),
  kpi_index     INT  NOT NULL CHECK (kpi_index IN (1, 2)),
  statement     TEXT NOT NULL,
  UNIQUE (competency_id, level, kpi_index)
);

ALTER TABLE competencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE competency_kpis ENABLE ROW LEVEL SECURITY;

-- Read-only reference data. The framework is a project deliverable: an advisor
-- chooses which part of it applies to their group but never edits it, so there
-- is no INSERT, UPDATE or DELETE policy and no write path from the app.
DROP POLICY IF EXISTS "competencies read" ON competencies;
CREATE POLICY "competencies read" ON competencies
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "competency kpis read" ON competency_kpis;
CREATE POLICY "competency kpis read" ON competency_kpis
  FOR SELECT TO authenticated USING (true);

-- Generated by scripts/generate-competency-seed.py. Do not hand-edit.
INSERT INTO competencies (code, name, display_order) VALUES
  ('problem_solving', 'Engineering Problem Solving', 1),
  ('documentation', 'Technical Documentation', 2),
  ('communication', 'Professional Communication', 3),
  ('digital_tools', 'Digital Tool Proficiency', 4),
  ('ethics', 'Responsibility & Ethics', 5),
  ('teamwork', 'Collaboration & Teamwork', 6)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name,
  display_order = EXCLUDED.display_order;

INSERT INTO competency_kpis (competency_id, level, kpi_index, statement)
SELECT c.id, v.level, v.kpi_index, v.statement
FROM (VALUES
  ('problem_solving', 1, 1, 'Identifies basic technical issues within assigned operational tasks.'),
  ('problem_solving', 1, 2, 'Observes and describes the approach engineers take to identify problems.'),
  ('problem_solving', 2, 1, 'Assists in diagnosing engineering problems with direct mentor guidance.'),
  ('problem_solving', 2, 2, 'Participates in solving simple technical tasks using established methods.'),
  ('problem_solving', 3, 1, 'Independently analyses engineering problems and evaluates data-based solutions.'),
  ('problem_solving', 3, 2, 'Proposes viable technical solutions for identified issues within a project.'),
  ('problem_solving', 4, 1, 'Develops optimized solutions for complex problems and anticipates risks.'),
  ('problem_solving', 4, 2, 'Mentors others in problem-solving approaches and improves process outcomes.'),
  ('documentation', 1, 1, 'Identifies technical documentation standards and reporting expectations used by the organisation.'),
  ('documentation', 1, 2, 'Recognizes specific types of technical documentation used in active engineering projects.'),
  ('documentation', 2, 1, 'Records task steps and technical results in project logs under mentor supervision.'),
  ('documentation', 2, 2, 'Maintains structured daily records of internship activities, observations, and findings.'),
  ('documentation', 3, 1, 'Produces clear technical summaries and progress reports independently.'),
  ('documentation', 3, 2, 'Organizes technical information clearly and logically in structured reports.'),
  ('documentation', 4, 1, 'Creates technical documentation that supports long-term knowledge transfer.'),
  ('documentation', 4, 2, 'Ensures high-quality technical deliverables that meet traceability and documentation standards.'),
  ('communication', 1, 1, 'Identifies key communication channels (meetings, email) used in the team.'),
  ('communication', 1, 2, 'Observes professional communication norms and reporting expectations.'),
  ('communication', 2, 1, 'Participates actively and appropriately in internal team communications and meetings.'),
  ('communication', 2, 2, 'Drafts clear, concise, and professional internal written correspondence.'),
  ('communication', 3, 1, 'Presents technical information clearly to peers and supervisors.'),
  ('communication', 3, 2, 'Facilitates standard technical discussions or small team meetings.'),
  ('communication', 4, 1, 'Communicates effectively with external stakeholders or clients under supervision.'),
  ('communication', 4, 2, 'Manages professional communication during conflicts, negotiations, or critical feedback.'),
  ('digital_tools', 1, 1, 'Correctly identifies primary software and digital platforms used by the organisation.'),
  ('digital_tools', 1, 2, 'Describes standard digital workflows and data entry requirements observed.'),
  ('digital_tools', 2, 1, 'Uses basic digital tool functions to document tasks and share progress under supervision.'),
  ('digital_tools', 2, 2, 'Accurately records project data in the digital tracking system following protocols.'),
  ('digital_tools', 3, 1, 'Independently utilizes advanced features of core digital tools for project tasks.'),
  ('digital_tools', 3, 2, 'Integrates data across multiple software platforms to complete engineering workflows.'),
  ('digital_tools', 4, 1, 'Troubleshoots complex software issues and optimizes digital tool configurations.'),
  ('digital_tools', 4, 2, 'Guides team members on best practices for digital workflows and data management.'),
  ('ethics', 1, 1, 'Consistently arrives on time and adheres to all workplace safety policies.'),
  ('ethics', 1, 2, 'Observes ethical standards and sustainability practices in current projects.'),
  ('ethics', 2, 1, 'Completes routine tasks within agreed-upon timeframes under supervision.'),
  ('ethics', 2, 2, 'Respects industry norms and professional standards in all assigned tasks.'),
  ('ethics', 3, 1, 'Consistently meets deadlines and manages time without requiring reminders.'),
  ('ethics', 3, 2, 'Independently applies ethical principles and sustainability in technical decisions.'),
  ('ethics', 4, 1, 'Anticipates potential project delays and proactively adjusts schedules.'),
  ('ethics', 4, 2, 'Takes full ownership of deliverables and promotes ethics/sustainability in the team.'),
  ('teamwork', 1, 1, 'Identifies the contributions of different professional roles in a project.'),
  ('teamwork', 1, 2, 'Shows respect for the colleagues and adheres to workplace diversity norms'),
  ('teamwork', 2, 1, 'Completes assigned portions of collaborative tasks reliably under supervision'),
  ('teamwork', 2, 2, 'Offers assistance to team members once own assigned tasks are completed'),
  ('teamwork', 3, 1, 'Constructively integrates feedback from team members into work outputs'),
  ('teamwork', 3, 2, 'Shares useful resources or technical insights with colleagues proactively.'),
  ('teamwork', 4, 1, 'Assists in resolving minor conflicts or technical misalignments in the team.'),
  ('teamwork', 4, 2, 'Mentors or guides newer team members and peers effectively during tasks.')
) AS v(code, level, kpi_index, statement)
JOIN competencies c ON c.code = v.code
ON CONFLICT (competency_id, level, kpi_index)
  DO UPDATE SET statement = EXCLUDED.statement;
